Capture output

diff --git a/.github/workflows/lbp_deploy_action.yml b/.github/workflows/lbp_deploy_action.yml
--- a/.github/workflows/lbp_deploy_action.yml
+++ b/.github/workflows/lbp_deploy_action.yml
@@ -106,10 +106,15 @@ jobs:
     - name: Liquibase Checks Flow
       id: lbp-policy-checks
       run: | 
-        CHECKS_STATUS=$(liquibase flow --classpath=liquibase-aws-extension.jar --flow-file=liquibase-checks.flowfile.yaml)
-        echo "Checks Status:"
-        echo "$CHECKS_STATUS"
-        echo "checks_status=$CHECKS_STATUS" >> $GITHUB_OUTPUT
+        CHECKS_STATUS=$(liquibase flow --classpath=liquibase-aws-extension.jar --flow-file=liquibase-checks.flowfile.yaml 2>&1)
+        EXIT_CODE=$?
+        if [ $EXIT_CODE -eq 1 ]; then
+          echo "Liquibase Checks Failed. Requires Manual Approval."
+          echo "checks_status=1" >> $GITHUB_OUTPUT
+        elif [ $EXIT_CODE -ne 0 ]; then
+          echo "Liquibase Checks Passed. No Approval Required."
+          echo "checks_status=0" >> $GITHUB_OUTPUT
+        fi
       
   manual-approval:
     runs-on: [self-hosted]
