Refactor (#31)
* Refactor Build

* Added session token

* deploy and premerge

* Adjustments

* Removed files

* Adding runAlways

* Moved checks

* Logging

* Bucketname

* Snowflake Connect

* Spacing

---------

Co-authored-by: Amy Smith <asmith@liquibase.com>

diff --git a/.github/workflows/lbp_premerge_action.yml b/.github/workflows/lbp_premerge_action.yml
--- a/.github/workflows/lbp_premerge_action.yml
+++ b/.github/workflows/lbp_premerge_action.yml
@@ -30,7 +30,7 @@ on:
 ###########################################################################
 env:
   # AWS S3 bucket is the host part of the S3 bucket
-  # AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
+  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
   
   # AWS Access credentials use by the Liquibase Pro S3 Extension
   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
@@ -65,9 +65,13 @@ env:
   ENVIRONMENT: DEV
   LB_TAG: ${{ github.ref_name }}
 
-  LIQUIBASE_REPORT_PATH: s3://${{ secrets.AWS_S3_BUCKET }}/gha_reports
+  # LIQUIBASE_REPORT_PATH: s3://${{ secrets.AWS_S3_BUCKET }}/gha_reports
+  LIQUIBASE_REPORT_PATH: reports
+  
   # Values: OFF, SEVERE, WARNING, INFO, FINE
   LIQUIBASE_LOG_LEVEL: INFO
+  LIQUIBASE_LOG_FORMAT: JSON_PRETTY
+  LIQUIBASE_LOG_FILE: logs/log.json  
   
   # Prevalidate Settings
   LB_CLONED_URL: "jdbc:sqlserver://${{ secrets.LIQUIBASE_HOSTNAME }}:${{ secrets.LIQUIBASE_PORT }};databaseName=${{ secrets.LIQUIBASE_DATABASE_NAME }}_eph;trustServerCertificate=true"
@@ -92,6 +96,27 @@ jobs:
     # Required to run commands for Cloning DB
     - name: Install MSSQL Client tools
       uses: ./.github/workflows/install-mssql-client-tools
+
+    - name: Liquibase Checks Flow
+      id: lbp-policy-checks
+      continue-on-error: true
+      run: | 
+        set +e
+        CHECKS_STATUS=$(liquibase flow --classpath=liquibase-aws-extension.jar --flow-file=liquibase-checks.flowfile.yaml 2>&1)
+        EXIT_CODE=$?
+        set -e
+        if [ $EXIT_CODE -eq 1 ]; then
+          echo "::error::Policy checks did not pass, but allowing merge."
+          echo "::error::In non-build environments, this deployment will require Manual Approval."
+          exit $EXIT_CODE
+        fi
         
     - name: Liquibase Premerge Flow
       run: liquibase flow --classpath=liquibase-aws-extension.jar --flow-file=liquibase-premerge.flowfile.yaml
+
+    - name: Upload Reports Artifact
+      if: always()
+      uses: ./.github/workflows/upload-reports
+      with:
+        job-type: deploy
+        upload-s3: true
